
mentorslist = [
    {
        'name': 'Million',
        'father_name': 'Meseret',
        'grand_father_name': 'Yirdaw',
        'Bio': 'I am a passionate educator with a Master\'s degree and a track record of academic excellence. With a dedication to fostering a dynamic learning environment, I bring 3 years of experience in guiding students towards success.',
        'experience': '3 years university lecturing',
        'photo': 'default.jpg',
        'email': 'millionmesi1@gmail.com',
        'phone_number': '0910120891',
        'password': 'Million1234!',
    },
     {
        'name': 'Betelihem',
        'father_name': 'Eyob',
        'grand_father_name': 'Yirdaw',
        'Bio': 'As a mentor, my goal is to inspire and empower students to reach their full potential, equipping them with the knowledge and skills needed to excel!',
        'experience': '2 years tutoring',
        'photo': 'default.jpg',
        'email': 'betelihem@gmail.com',
        'phone_number': '0910120891',
        'password': 'Million1234!',
    },
    {
        'name': 'Elias',
        'father_name': 'Ebro',
        'grand_father_name': 'Yirdaw',
        'Bio': 'As a mentor, my goal is to inspire and empower students to reach their full potential, equipping them with the knowledge and skills needed to excel!',
        'experience': '2 years tutoring',
        'photo': 'default.jpg',
        'email': 'betelihem@gmail.com',
        'phone_number': '0910120891',
        'password': 'Million1234!',
    },
    {
        'name': 'Debe',
        'father_name': 'man',
        'grand_father_name': 'Yirdaw',
        'Bio': 'As a mentor, my goal is to inspire and empower students to reach their full potential, equipping them with the knowledge and skills needed to excel!',
        'experience': '2 years tutoring',
        'photo': 'default.jpg',
        'email': 'betelihem@gmail.com',
        'phone_number': '0910120891',
        'password': 'Million1234!',
    },
    {
        'name': 'Biniamin',
        'father_name': 'Zewedu',
        'grand_father_name': 'Yirdaw',
        'Bio': 'As a mentor, my goal is to inspire and empower students to reach their full potential, equipping them with the knowledge and skills needed to excel!',
        'experience': '2 years tutoring',
        'photo': 'default.jpg',
        'email': 'betelihem@gmail.com',
        'phone_number': '0910120891',
        'password': 'Million1234!',
    }
]